POST http://localhost:8083/connectors
Content-Type: application/json

< ./connectors/config/mysql-connect.json

###
GET http://localhost:8083/

###
GET http://localhost:8083/connectors/

###
GET http://localhost:8083/connectors?expand=status

###
GET http://localhost:8083/connectors?expand=info

###
GET http://localhost:8083/connectors/user-pets-connector

###
DELETE http://localhost:8083/connectors/user-pets-connector

###
GET http://localhost:8083/connectors/user-pets-connector/config

###
GET http://localhost:8083/connectors/user-pets-connector/status

###  schema registry
GET http://localhost:8081/subjects

###
GET http://localhost:8081/subjects/kafka_connect_studies.kafka_connect_studies.pets-value/versions

###
GET http://localhost:8081/subjects/kafka_connect_studies.kafka_connect_studies.pets-value/versions/latest

###
GET http://localhost:8081/subjects/kafka_connect_studies.kafka_connect_studies.users-value/versions/latest

###
GET http://localhost:8081/schemas/ids/1

###
GET http://localhost:8081/schemas/types

